name: example
description: A web-based Flutter example application demonstrating the capabilities of the svg_painter package.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  svg_painter_annotation:
    path: ../svg_painter_annotation
  svg_painter_fixtures:
    path: ../svg_painter_fixtures

dev_dependencies:
  svg_painter:
    path: ../svg_painter
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
