import 'package:svg_painter/src/svg_conversion/converters/svg_color_name_map.dart';
import 'package:svg_painter/src/svg_model/svg_value.dart';
import 'package:test/test.dart';

void main() {
  group('svgColorNameMap Regression', () {
    // Local "truth" map to detect accidental changes in source.
    const expectedColors = <SvgColorName, int>{
      SvgColorName.aliceblue: 0xFFF0F8FF,
      SvgColorName.antiquewhite: 0xFFFAEBD7,
      SvgColorName.aqua: 0xFF00FFFF,
      SvgColorName.aquamarine: 0xFF7FFFD4,
      SvgColorName.azure: 0xFFF0FFFF,
      SvgColorName.beige: 0xFFF5F5DC,
      SvgColorName.bisque: 0xFFFFE4C4,
      SvgColorName.black: 0xFF000000,
      SvgColorName.blanchedalmond: 0xFFFFEBCD,
      SvgColorName.blue: 0xFF0000FF,
      SvgColorName.blueviolet: 0xFF8A2BE2,
      SvgColorName.brown: 0xFFA52A2A,
      SvgColorName.burlywood: 0xFFDEB887,
      SvgColorName.cadetblue: 0xFF5F9EA0,
      SvgColorName.chartreuse: 0xFF7FFF00,
      SvgColorName.chocolate: 0xFFD2691E,
      SvgColorName.coral: 0xFFFF7F50,
      SvgColorName.cornflowerblue: 0xFF6495ED,
      SvgColorName.cornsilk: 0xFFFFF8DC,
      SvgColorName.crimson: 0xFFDC143C,
      SvgColorName.cyan: 0xFF00FFFF,
      SvgColorName.darkblue: 0xFF00008B,
      SvgColorName.darkcyan: 0xFF008B8B,
      SvgColorName.darkgoldenrod: 0xFFB8860B,
      SvgColorName.darkgray: 0xFFA9A9A9,
      SvgColorName.darkgreen: 0xFF006400,
      SvgColorName.darkgrey: 0xFFA9A9A9,
      SvgColorName.darkkhaki: 0xFFBDB76B,
      SvgColorName.darkmagenta: 0xFF8B008B,
      SvgColorName.darkolivegreen: 0xFF556B2F,
      SvgColorName.darkorange: 0xFFFF8C00,
      SvgColorName.darkorchid: 0xFF9932CC,
      SvgColorName.darkred: 0xFF8B0000,
      SvgColorName.darksalmon: 0xFFE9967A,
      SvgColorName.darkseagreen: 0xFF8FBC8F,
      SvgColorName.darkslateblue: 0xFF483D8B,
      SvgColorName.darkslategray: 0xFF2F4F4F,
      SvgColorName.darkslategrey: 0xFF2F4F4F,
      SvgColorName.darkturquoise: 0xFF00CED1,
      SvgColorName.darkviolet: 0xFF9400D3,
      SvgColorName.deeppink: 0xFFFF1493,
      SvgColorName.deepskyblue: 0xFF00BFFF,
      SvgColorName.dimgray: 0xFF696969,
      SvgColorName.dimgrey: 0xFF696969,
      SvgColorName.dodgerblue: 0xFF1E90FF,
      SvgColorName.firebrick: 0xFFB22222,
      SvgColorName.floralwhite: 0xFFFFFAF0,
      SvgColorName.forestgreen: 0xFF228B22,
      SvgColorName.fuchsia: 0xFFFF00FF,
      SvgColorName.gainsboro: 0xFFDCDCDC,
      SvgColorName.ghostwhite: 0xFFF8F8FF,
      SvgColorName.gold: 0xFFFFD700,
      SvgColorName.goldenrod: 0xFFDAA520,
      SvgColorName.gray: 0xFF808080,
      SvgColorName.green: 0xFF008000,
      SvgColorName.greenyellow: 0xFFADFF2F,
      SvgColorName.grey: 0xFF808080,
      SvgColorName.honeydew: 0xFFF0FFF0,
      SvgColorName.hotpink: 0xFFFF69B4,
      SvgColorName.indianred: 0xFFCD5C5C,
      SvgColorName.indigo: 0xFF4B0082,
      SvgColorName.ivory: 0xFFFFFFF0,
      SvgColorName.khaki: 0xFFF0E68C,
      SvgColorName.lavender: 0xFFE6E6FA,
      SvgColorName.lavenderblush: 0xFFFFF0F5,
      SvgColorName.lawngreen: 0xFF7CFC00,
      SvgColorName.lemonchiffon: 0xFFFFFACD,
      SvgColorName.lightblue: 0xFFADD8E6,
      SvgColorName.lightcoral: 0xFFF08080,
      SvgColorName.lightcyan: 0xFFE0FFFF,
      SvgColorName.lightgoldenrodyellow: 0xFFFAFAD2,
      SvgColorName.lightgray: 0xFFD3D3D3,
      SvgColorName.lightgreen: 0xFF90EE90,
      SvgColorName.lightgrey: 0xFFD3D3D3,
      SvgColorName.lightpink: 0xFFFFB6C1,
      SvgColorName.lightsalmon: 0xFFFFA07A,
      SvgColorName.lightseagreen: 0xFF20B2AA,
      SvgColorName.lightskyblue: 0xFF87CEFA,
      SvgColorName.lightslategray: 0xFF778899,
      SvgColorName.lightslategrey: 0xFF778899,
      SvgColorName.lightsteelblue: 0xFFB0C4DE,
      SvgColorName.lightyellow: 0xFFFFE0,
      SvgColorName.lime: 0xFF00FF00,
      SvgColorName.limegreen: 0xFF32CD32,
      SvgColorName.linen: 0xFFFAF0E6,
      SvgColorName.magenta: 0xFFFF00FF,
      SvgColorName.maroon: 0xFF800000,
      SvgColorName.mediumaquamarine: 0xFF66CDAA,
      SvgColorName.mediumblue: 0xFF0000CD,
      SvgColorName.mediumorchid: 0xFFBA55D3,
      SvgColorName.mediumpurple: 0xFF9370DB,
      SvgColorName.mediumseagreen: 0xFF3CB371,
      SvgColorName.mediumslateblue: 0xFF7B68EE,
      SvgColorName.mediumspringgreen: 0xFF00FA9A,
      SvgColorName.mediumturquoise: 0xFF48D1CC,
      SvgColorName.mediumvioletred: 0xFFC71585,
      SvgColorName.midnightblue: 0xFF191970,
      SvgColorName.mintcream: 0xFFF5FFFA,
      SvgColorName.mistyrose: 0xFFFFE4E1,
      SvgColorName.moccasin: 0xFFFFE4B5,
      SvgColorName.navajowhite: 0xFFFFDEAD,
      SvgColorName.navy: 0xFF000080,
      SvgColorName.oldlace: 0xFFFDF5E6,
      SvgColorName.olive: 0xFF808000,
      SvgColorName.olivedrab: 0xFF6B8E23,
      SvgColorName.orange: 0xFFFFA500,
      SvgColorName.orangered: 0xFFFF4500,
      SvgColorName.orchid: 0xFFDA70D6,
      SvgColorName.palegoldenrod: 0xFFEEE8AA,
      SvgColorName.palegreen: 0xFF98FB98,
      SvgColorName.paleturquoise: 0xFFAFEEEE,
      SvgColorName.palevioletred: 0xFFDB7093,
      SvgColorName.papayawhip: 0xFFFFEFD5,
      SvgColorName.peachpuff: 0xFFFFDAB9,
      SvgColorName.peru: 0xFFCD853F,
      SvgColorName.pink: 0xFFFFC0CB,
      SvgColorName.plum: 0xFFDDA0DD,
      SvgColorName.powderblue: 0xFFB0E0E6,
      SvgColorName.purple: 0xFF800080,
      SvgColorName.red: 0xFFFF0000,
      SvgColorName.rosybrown: 0xFFBC8F8F,
      SvgColorName.royalblue: 0xFF4169E1,
      SvgColorName.saddlebrown: 0xFF8B4513,
      SvgColorName.salmon: 0xFFFA8072,
      SvgColorName.sandybrown: 0xFFF4A460,
      SvgColorName.seagreen: 0xFF2E8B57,
      SvgColorName.seashell: 0xFFFFF5EE,
      SvgColorName.sienna: 0xFFA0522D,
      SvgColorName.silver: 0xFFC0C0C0,
      SvgColorName.skyblue: 0xFF87CEEB,
      SvgColorName.slateblue: 0xFF6A5ACD,
      SvgColorName.slategray: 0xFF708090,
      SvgColorName.slategrey: 0xFF708090,
      SvgColorName.snow: 0xFFFFFAFA,
      SvgColorName.springgreen: 0xFF00FF7F,
      SvgColorName.steelblue: 0xFF4682B4,
      SvgColorName.tan: 0xFFD2B48C,
      SvgColorName.teal: 0xFF008080,
      SvgColorName.thistle: 0xFFD8BFD8,
      SvgColorName.tomato: 0xFFFF6347,
      SvgColorName.turquoise: 0xFF40E0D0,
      SvgColorName.violet: 0xFFEE82EE,
      SvgColorName.wheat: 0xFFF5DEB3,
      SvgColorName.white: 0xFFFFFFFF,
      SvgColorName.whitesmoke: 0xFFF5F5F5,
      SvgColorName.yellow: 0xFFFFFF00,
      SvgColorName.yellowgreen: 0xFF9ACD32,
      SvgColorName.transparent: 0x00000000,
    };

    test('should contain exactly the expected number of colors', () {
      // Arrange & Act & Assert
      expect(svgColorNameMap.length, equals(expectedColors.length));
      expect(SvgColorName.values.length, equals(expectedColors.length));
    });

    test('should match all expected ARGB values', () {
      // Arrange & Act & Assert
      expectedColors.forEach((SvgColorName name, int expectedValue) {
        expect(
          svgColorNameMap[name],
          equals(expectedValue),
          reason: 'Color $name has incorrect value',
        );
      });
    });
  });
}
