// Mocks generated by Mockito 5.4.6 from annotations
// in svg_painter/test/src/generation/asset_loader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i15;

import 'package:analyzer/dart/constant/value.dart' as _i2;
import 'package:analyzer/dart/element/element.dart' as _i7;
import 'package:analyzer/dart/element/type.dart' as _i3;
import 'package:build/build.dart' as _i14;
import 'package:build/src/asset_id.dart' as _i6;
import 'package:build/src/resolver.dart' as _i8;
import 'package:build/src/resource.dart' as _i17;
import 'package:crypto/crypto.dart' as _i11;
import 'package:glob/glob.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:package_config/package_config_types.dart' as _i9;
import 'package:source_gen/src/constants/reader.dart' as _i4;
import 'package:source_gen/src/constants/revive.dart' as _i5;
import 'package:source_gen/src/type_checker.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDartObject_0 extends _i1.SmartFake implements _i2.DartObject {
  _FakeDartObject_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSymbol_1 extends _i1.SmartFake implements Symbol {
  _FakeSymbol_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDartType_2 extends _i1.SmartFake implements _i3.DartType {
  _FakeDartType_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeConstantReader_3 extends _i1.SmartFake implements _i4.ConstantReader {
  _FakeConstantReader_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRevivable_4 extends _i1.SmartFake implements _i5.Revivable {
  _FakeRevivable_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAssetId_5 extends _i1.SmartFake implements _i6.AssetId {
  _FakeAssetId_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeLibraryElement_6 extends _i1.SmartFake implements _i7.LibraryElement {
  _FakeLibraryElement_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResolver_7 extends _i1.SmartFake implements _i8.Resolver {
  _FakeResolver_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakePackageConfig_8 extends _i1.SmartFake implements _i9.PackageConfig {
  _FakePackageConfig_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDigest_10 extends _i1.SmartFake implements _i11.Digest {
  _FakeDigest_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [ConstantReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockConstantReader extends _i1.Mock implements _i4.ConstantReader {
  @override
  bool get isLiteral =>
      (super.noSuchMethod(
            Invocation.getter(#isLiteral),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.DartObject get objectValue =>
      (super.noSuchMethod(
            Invocation.getter(#objectValue),
            returnValue: _FakeDartObject_0(this, Invocation.getter(#objectValue)),
            returnValueForMissingStub: _FakeDartObject_0(this, Invocation.getter(#objectValue)),
          )
          as _i2.DartObject);

  @override
  bool get isNull =>
      (super.noSuchMethod(
            Invocation.getter(#isNull),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isBool =>
      (super.noSuchMethod(
            Invocation.getter(#isBool),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get boolValue =>
      (super.noSuchMethod(
            Invocation.getter(#boolValue),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInt =>
      (super.noSuchMethod(
            Invocation.getter(#isInt),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get intValue =>
      (super.noSuchMethod(
            Invocation.getter(#intValue),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isDouble =>
      (super.noSuchMethod(
            Invocation.getter(#isDouble),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get doubleValue =>
      (super.noSuchMethod(
            Invocation.getter(#doubleValue),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isString =>
      (super.noSuchMethod(
            Invocation.getter(#isString),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get stringValue =>
      (super.noSuchMethod(
            Invocation.getter(#stringValue),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#stringValue)),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#stringValue),
            ),
          )
          as String);

  @override
  bool get isSymbol =>
      (super.noSuchMethod(
            Invocation.getter(#isSymbol),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Symbol get symbolValue =>
      (super.noSuchMethod(
            Invocation.getter(#symbolValue),
            returnValue: _FakeSymbol_1(this, Invocation.getter(#symbolValue)),
            returnValueForMissingStub: _FakeSymbol_1(this, Invocation.getter(#symbolValue)),
          )
          as Symbol);

  @override
  bool get isType =>
      (super.noSuchMethod(
            Invocation.getter(#isType),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.DartType get typeValue =>
      (super.noSuchMethod(
            Invocation.getter(#typeValue),
            returnValue: _FakeDartType_2(this, Invocation.getter(#typeValue)),
            returnValueForMissingStub: _FakeDartType_2(this, Invocation.getter(#typeValue)),
          )
          as _i3.DartType);

  @override
  bool get isMap =>
      (super.noSuchMethod(
            Invocation.getter(#isMap),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<_i2.DartObject?, _i2.DartObject?> get mapValue =>
      (super.noSuchMethod(
            Invocation.getter(#mapValue),
            returnValue: <_i2.DartObject?, _i2.DartObject?>{},
            returnValueForMissingStub: <_i2.DartObject?, _i2.DartObject?>{},
          )
          as Map<_i2.DartObject?, _i2.DartObject?>);

  @override
  bool get isList =>
      (super.noSuchMethod(
            Invocation.getter(#isList),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.DartObject> get listValue =>
      (super.noSuchMethod(
            Invocation.getter(#listValue),
            returnValue: <_i2.DartObject>[],
            returnValueForMissingStub: <_i2.DartObject>[],
          )
          as List<_i2.DartObject>);

  @override
  bool get isSet =>
      (super.noSuchMethod(
            Invocation.getter(#isSet),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<_i2.DartObject> get setValue =>
      (super.noSuchMethod(
            Invocation.getter(#setValue),
            returnValue: <_i2.DartObject>{},
            returnValueForMissingStub: <_i2.DartObject>{},
          )
          as Set<_i2.DartObject>);

  @override
  bool instanceOf(_i13.TypeChecker? checker) =>
      (super.noSuchMethod(
            Invocation.method(#instanceOf, [checker]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.ConstantReader read(String? field) =>
      (super.noSuchMethod(
            Invocation.method(#read, [field]),
            returnValue: _FakeConstantReader_3(this, Invocation.method(#read, [field])),
            returnValueForMissingStub: _FakeConstantReader_3(
              this,
              Invocation.method(#read, [field]),
            ),
          )
          as _i4.ConstantReader);

  @override
  _i4.ConstantReader? peek(String? field) =>
      (super.noSuchMethod(Invocation.method(#peek, [field]), returnValueForMissingStub: null)
          as _i4.ConstantReader?);

  @override
  _i5.Revivable revive() =>
      (super.noSuchMethod(
            Invocation.method(#revive, []),
            returnValue: _FakeRevivable_4(this, Invocation.method(#revive, [])),
            returnValueForMissingStub: _FakeRevivable_4(this, Invocation.method(#revive, [])),
          )
          as _i5.Revivable);
}

/// A class which mocks [BuildStep].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildStep extends _i1.Mock implements _i14.BuildStep {
  @override
  _i6.AssetId get inputId =>
      (super.noSuchMethod(
            Invocation.getter(#inputId),
            returnValue: _FakeAssetId_5(this, Invocation.getter(#inputId)),
            returnValueForMissingStub: _FakeAssetId_5(this, Invocation.getter(#inputId)),
          )
          as _i6.AssetId);

  @override
  _i10.Future<_i7.LibraryElement> get inputLibrary =>
      (super.noSuchMethod(
            Invocation.getter(#inputLibrary),
            returnValue: _i10.Future<_i7.LibraryElement>.value(
              _FakeLibraryElement_6(this, Invocation.getter(#inputLibrary)),
            ),
            returnValueForMissingStub: _i10.Future<_i7.LibraryElement>.value(
              _FakeLibraryElement_6(this, Invocation.getter(#inputLibrary)),
            ),
          )
          as _i10.Future<_i7.LibraryElement>);

  @override
  _i8.Resolver get resolver =>
      (super.noSuchMethod(
            Invocation.getter(#resolver),
            returnValue: _FakeResolver_7(this, Invocation.getter(#resolver)),
            returnValueForMissingStub: _FakeResolver_7(this, Invocation.getter(#resolver)),
          )
          as _i8.Resolver);

  @override
  Iterable<_i6.AssetId> get allowedOutputs =>
      (super.noSuchMethod(
            Invocation.getter(#allowedOutputs),
            returnValue: <_i6.AssetId>[],
            returnValueForMissingStub: <_i6.AssetId>[],
          )
          as Iterable<_i6.AssetId>);

  @override
  _i10.Future<_i9.PackageConfig> get packageConfig =>
      (super.noSuchMethod(
            Invocation.getter(#packageConfig),
            returnValue: _i10.Future<_i9.PackageConfig>.value(
              _FakePackageConfig_8(this, Invocation.getter(#packageConfig)),
            ),
            returnValueForMissingStub: _i10.Future<_i9.PackageConfig>.value(
              _FakePackageConfig_8(this, Invocation.getter(#packageConfig)),
            ),
          )
          as _i10.Future<_i9.PackageConfig>);

  @override
  _i10.Future<List<int>> readAsBytes(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, [id]),
            returnValue: _i10.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i10.Future<List<int>>.value(<int>[]),
          )
          as _i10.Future<List<int>>);

  @override
  _i10.Future<String> readAsString(
    _i6.AssetId? id, {
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [id], {#encoding: encoding}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [id], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [id], {#encoding: encoding}),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<bool> canRead(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [id]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Stream<_i6.AssetId> findAssets(_i16.Glob? glob) =>
      (super.noSuchMethod(
            Invocation.method(#findAssets, [glob]),
            returnValue: _i10.Stream<_i6.AssetId>.empty(),
            returnValueForMissingStub: _i10.Stream<_i6.AssetId>.empty(),
          )
          as _i10.Stream<_i6.AssetId>);

  @override
  _i10.Future<void> writeAsBytes(_i6.AssetId? id, _i10.FutureOr<List<int>>? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#writeAsBytes, [id, bytes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> writeAsString(
    _i6.AssetId? id,
    _i10.FutureOr<String>? contents, {
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeAsString, [id, contents], {#encoding: encoding}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<T> fetchResource<T>(_i17.Resource<T>? resource) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResource, [resource]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(this, Invocation.method(#fetchResource, [resource])),
                  (T v) => _i10.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(this, Invocation.method(#fetchResource, [resource])),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(this, Invocation.method(#fetchResource, [resource])),
                  (T v) => _i10.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(this, Invocation.method(#fetchResource, [resource])),
          )
          as _i10.Future<T>);

  @override
  T trackStage<T>(String? label, T Function()? action, {bool? isExternal = false}) =>
      (super.noSuchMethod(
            Invocation.method(#trackStage, [label, action], {#isExternal: isExternal}),
            returnValue: _i12.dummyValue<T>(
              this,
              Invocation.method(#trackStage, [label, action], {#isExternal: isExternal}),
            ),
            returnValueForMissingStub: _i12.dummyValue<T>(
              this,
              Invocation.method(#trackStage, [label, action], {#isExternal: isExternal}),
            ),
          )
          as T);

  @override
  void reportUnusedAssets(Iterable<_i6.AssetId>? ids) => super.noSuchMethod(
    Invocation.method(#reportUnusedAssets, [ids]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i11.Digest> digest(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#digest, [id]),
            returnValue: _i10.Future<_i11.Digest>.value(
              _FakeDigest_10(this, Invocation.method(#digest, [id])),
            ),
            returnValueForMissingStub: _i10.Future<_i11.Digest>.value(
              _FakeDigest_10(this, Invocation.method(#digest, [id])),
            ),
          )
          as _i10.Future<_i11.Digest>);
}

/// A class which mocks [TypeChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockTypeChecker extends _i1.Mock implements _i13.TypeChecker {
  @override
  _i2.DartObject? firstAnnotationOf(Object? element, {bool? throwOnUnresolved = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #firstAnnotationOf,
              [element],
              {#throwOnUnresolved: throwOnUnresolved},
            ),
            returnValueForMissingStub: null,
          )
          as _i2.DartObject?);

  @override
  bool hasAnnotationOf(_i7.Element? element, {bool? throwOnUnresolved = true}) =>
      (super.noSuchMethod(
            Invocation.method(#hasAnnotationOf, [element], {#throwOnUnresolved: throwOnUnresolved}),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.DartObject? firstAnnotationOfExact(_i7.Element? element, {bool? throwOnUnresolved = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #firstAnnotationOfExact,
              [element],
              {#throwOnUnresolved: throwOnUnresolved},
            ),
            returnValueForMissingStub: null,
          )
          as _i2.DartObject?);

  @override
  bool hasAnnotationOfExact(_i7.Element? element, {bool? throwOnUnresolved = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasAnnotationOfExact,
              [element],
              {#throwOnUnresolved: throwOnUnresolved},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<_i2.DartObject> annotationsOf(Object? element, {bool? throwOnUnresolved = true}) =>
      (super.noSuchMethod(
            Invocation.method(#annotationsOf, [element], {#throwOnUnresolved: throwOnUnresolved}),
            returnValue: <_i2.DartObject>[],
            returnValueForMissingStub: <_i2.DartObject>[],
          )
          as Iterable<_i2.DartObject>);

  @override
  Iterable<_i2.DartObject> annotationsOfExact(
    _i7.Element? element, {
    bool? throwOnUnresolved = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #annotationsOfExact,
              [element],
              {#throwOnUnresolved: throwOnUnresolved},
            ),
            returnValue: <_i2.DartObject>[],
            returnValueForMissingStub: <_i2.DartObject>[],
          )
          as Iterable<_i2.DartObject>);

  @override
  bool isAssignableFrom(_i7.Element? element) =>
      (super.noSuchMethod(
            Invocation.method(#isAssignableFrom, [element]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isAssignableFromType(_i3.DartType? staticType) =>
      (super.noSuchMethod(
            Invocation.method(#isAssignableFromType, [staticType]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isExactly(_i7.Element? element) =>
      (super.noSuchMethod(
            Invocation.method(#isExactly, [element]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isExactlyType(_i3.DartType? staticType) =>
      (super.noSuchMethod(
            Invocation.method(#isExactlyType, [staticType]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isSuperOf(_i7.Element? element) =>
      (super.noSuchMethod(
            Invocation.method(#isSuperOf, [element]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isSuperTypeOf(_i3.DartType? staticType) =>
      (super.noSuchMethod(
            Invocation.method(#isSuperTypeOf, [staticType]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
