// Mocks generated by Mockito 5.4.6 from annotations
// in svg_painter/test/src/svg_painter_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i15;

import 'package:analyzer/dart/constant/value.dart' as _i2;
import 'package:analyzer/dart/element/element.dart' as _i7;
import 'package:analyzer/dart/element/nullability_suffix.dart' as _i18;
import 'package:analyzer/dart/element/type.dart' as _i3;
import 'package:analyzer/dart/element/type_visitor.dart' as _i19;
import 'package:build/src/asset_id.dart' as _i6;
import 'package:build/src/build_step.dart' as _i14;
import 'package:build/src/resolver.dart' as _i8;
import 'package:build/src/resource.dart' as _i17;
import 'package:crypto/crypto.dart' as _i11;
import 'package:glob/glob.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:package_config/package_config_types.dart' as _i9;
import 'package:source_gen/src/constants/reader.dart' as _i4;
import 'package:source_gen/src/constants/revive.dart' as _i5;
import 'package:source_gen/src/type_checker.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDartObject_0 extends _i1.SmartFake implements _i2.DartObject {
  _FakeDartObject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSymbol_1 extends _i1.SmartFake implements Symbol {
  _FakeSymbol_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDartType_2 extends _i1.SmartFake implements _i3.DartType {
  _FakeDartType_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConstantReader_3 extends _i1.SmartFake
    implements _i4.ConstantReader {
  _FakeConstantReader_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRevivable_4 extends _i1.SmartFake implements _i5.Revivable {
  _FakeRevivable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssetId_5 extends _i1.SmartFake implements _i6.AssetId {
  _FakeAssetId_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLibraryElement_6 extends _i1.SmartFake
    implements _i7.LibraryElement {
  _FakeLibraryElement_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResolver_7 extends _i1.SmartFake implements _i8.Resolver {
  _FakeResolver_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePackageConfig_8 extends _i1.SmartFake implements _i9.PackageConfig {
  _FakePackageConfig_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDigest_10 extends _i1.SmartFake implements _i11.Digest {
  _FakeDigest_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeElement_11 extends _i1.SmartFake implements _i7.Element {
  _FakeElement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFragment_12 extends _i1.SmartFake implements _i7.Fragment {
  _FakeFragment_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeElementKind_13 extends _i1.SmartFake implements _i7.ElementKind {
  _FakeElementKind_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetadata_14 extends _i1.SmartFake implements _i7.Metadata {
  _FakeMetadata_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConstantReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockConstantReader extends _i1.Mock implements _i4.ConstantReader {
  @override
  bool get isLiteral =>
      (super.noSuchMethod(
            Invocation.getter(#isLiteral),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.DartObject get objectValue =>
      (super.noSuchMethod(
            Invocation.getter(#objectValue),
            returnValue: _FakeDartObject_0(
              this,
              Invocation.getter(#objectValue),
            ),
            returnValueForMissingStub: _FakeDartObject_0(
              this,
              Invocation.getter(#objectValue),
            ),
          )
          as _i2.DartObject);

  @override
  bool get isNull =>
      (super.noSuchMethod(
            Invocation.getter(#isNull),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isBool =>
      (super.noSuchMethod(
            Invocation.getter(#isBool),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get boolValue =>
      (super.noSuchMethod(
            Invocation.getter(#boolValue),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInt =>
      (super.noSuchMethod(
            Invocation.getter(#isInt),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get intValue =>
      (super.noSuchMethod(
            Invocation.getter(#intValue),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isDouble =>
      (super.noSuchMethod(
            Invocation.getter(#isDouble),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get doubleValue =>
      (super.noSuchMethod(
            Invocation.getter(#doubleValue),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isString =>
      (super.noSuchMethod(
            Invocation.getter(#isString),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get stringValue =>
      (super.noSuchMethod(
            Invocation.getter(#stringValue),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#stringValue),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#stringValue),
            ),
          )
          as String);

  @override
  bool get isSymbol =>
      (super.noSuchMethod(
            Invocation.getter(#isSymbol),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Symbol get symbolValue =>
      (super.noSuchMethod(
            Invocation.getter(#symbolValue),
            returnValue: _FakeSymbol_1(this, Invocation.getter(#symbolValue)),
            returnValueForMissingStub: _FakeSymbol_1(
              this,
              Invocation.getter(#symbolValue),
            ),
          )
          as Symbol);

  @override
  bool get isType =>
      (super.noSuchMethod(
            Invocation.getter(#isType),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.DartType get typeValue =>
      (super.noSuchMethod(
            Invocation.getter(#typeValue),
            returnValue: _FakeDartType_2(this, Invocation.getter(#typeValue)),
            returnValueForMissingStub: _FakeDartType_2(
              this,
              Invocation.getter(#typeValue),
            ),
          )
          as _i3.DartType);

  @override
  bool get isMap =>
      (super.noSuchMethod(
            Invocation.getter(#isMap),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<_i2.DartObject?, _i2.DartObject?> get mapValue =>
      (super.noSuchMethod(
            Invocation.getter(#mapValue),
            returnValue: <_i2.DartObject?, _i2.DartObject?>{},
            returnValueForMissingStub: <_i2.DartObject?, _i2.DartObject?>{},
          )
          as Map<_i2.DartObject?, _i2.DartObject?>);

  @override
  bool get isList =>
      (super.noSuchMethod(
            Invocation.getter(#isList),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.DartObject> get listValue =>
      (super.noSuchMethod(
            Invocation.getter(#listValue),
            returnValue: <_i2.DartObject>[],
            returnValueForMissingStub: <_i2.DartObject>[],
          )
          as List<_i2.DartObject>);

  @override
  bool get isSet =>
      (super.noSuchMethod(
            Invocation.getter(#isSet),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<_i2.DartObject> get setValue =>
      (super.noSuchMethod(
            Invocation.getter(#setValue),
            returnValue: <_i2.DartObject>{},
            returnValueForMissingStub: <_i2.DartObject>{},
          )
          as Set<_i2.DartObject>);

  @override
  bool instanceOf(_i13.TypeChecker? checker) =>
      (super.noSuchMethod(
            Invocation.method(#instanceOf, [checker]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.ConstantReader read(String? field) =>
      (super.noSuchMethod(
            Invocation.method(#read, [field]),
            returnValue: _FakeConstantReader_3(
              this,
              Invocation.method(#read, [field]),
            ),
            returnValueForMissingStub: _FakeConstantReader_3(
              this,
              Invocation.method(#read, [field]),
            ),
          )
          as _i4.ConstantReader);

  @override
  _i4.ConstantReader? peek(String? field) =>
      (super.noSuchMethod(
            Invocation.method(#peek, [field]),
            returnValueForMissingStub: null,
          )
          as _i4.ConstantReader?);

  @override
  _i5.Revivable revive() =>
      (super.noSuchMethod(
            Invocation.method(#revive, []),
            returnValue: _FakeRevivable_4(this, Invocation.method(#revive, [])),
            returnValueForMissingStub: _FakeRevivable_4(
              this,
              Invocation.method(#revive, []),
            ),
          )
          as _i5.Revivable);
}

/// A class which mocks [BuildStep].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildStep extends _i1.Mock implements _i14.BuildStep {
  @override
  _i6.AssetId get inputId =>
      (super.noSuchMethod(
            Invocation.getter(#inputId),
            returnValue: _FakeAssetId_5(this, Invocation.getter(#inputId)),
            returnValueForMissingStub: _FakeAssetId_5(
              this,
              Invocation.getter(#inputId),
            ),
          )
          as _i6.AssetId);

  @override
  _i10.Future<_i7.LibraryElement> get inputLibrary =>
      (super.noSuchMethod(
            Invocation.getter(#inputLibrary),
            returnValue: _i10.Future<_i7.LibraryElement>.value(
              _FakeLibraryElement_6(this, Invocation.getter(#inputLibrary)),
            ),
            returnValueForMissingStub: _i10.Future<_i7.LibraryElement>.value(
              _FakeLibraryElement_6(this, Invocation.getter(#inputLibrary)),
            ),
          )
          as _i10.Future<_i7.LibraryElement>);

  @override
  _i8.Resolver get resolver =>
      (super.noSuchMethod(
            Invocation.getter(#resolver),
            returnValue: _FakeResolver_7(this, Invocation.getter(#resolver)),
            returnValueForMissingStub: _FakeResolver_7(
              this,
              Invocation.getter(#resolver),
            ),
          )
          as _i8.Resolver);

  @override
  Iterable<_i6.AssetId> get allowedOutputs =>
      (super.noSuchMethod(
            Invocation.getter(#allowedOutputs),
            returnValue: <_i6.AssetId>[],
            returnValueForMissingStub: <_i6.AssetId>[],
          )
          as Iterable<_i6.AssetId>);

  @override
  _i10.Future<_i9.PackageConfig> get packageConfig =>
      (super.noSuchMethod(
            Invocation.getter(#packageConfig),
            returnValue: _i10.Future<_i9.PackageConfig>.value(
              _FakePackageConfig_8(this, Invocation.getter(#packageConfig)),
            ),
            returnValueForMissingStub: _i10.Future<_i9.PackageConfig>.value(
              _FakePackageConfig_8(this, Invocation.getter(#packageConfig)),
            ),
          )
          as _i10.Future<_i9.PackageConfig>);

  @override
  _i10.Future<List<int>> readAsBytes(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, [id]),
            returnValue: _i10.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i10.Future<List<int>>.value(<int>[]),
          )
          as _i10.Future<List<int>>);

  @override
  _i10.Future<String> readAsString(
    _i6.AssetId? id, {
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [id], {#encoding: encoding}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [id], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [id], {#encoding: encoding}),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<bool> canRead(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#canRead, [id]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Stream<_i6.AssetId> findAssets(_i16.Glob? glob) =>
      (super.noSuchMethod(
            Invocation.method(#findAssets, [glob]),
            returnValue: _i10.Stream<_i6.AssetId>.empty(),
            returnValueForMissingStub: _i10.Stream<_i6.AssetId>.empty(),
          )
          as _i10.Stream<_i6.AssetId>);

  @override
  _i10.Future<void> writeAsBytes(
    _i6.AssetId? id,
    _i10.FutureOr<List<int>>? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeAsBytes, [id, bytes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> writeAsString(
    _i6.AssetId? id,
    _i10.FutureOr<String>? contents, {
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [id, contents],
              {#encoding: encoding},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<T> fetchResource<T>(_i17.Resource<T>? resource) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResource, [resource]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#fetchResource, [resource]),
                  ),
                  (T v) => _i10.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#fetchResource, [resource]),
                ),
            returnValueForMissingStub:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#fetchResource, [resource]),
                  ),
                  (T v) => _i10.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#fetchResource, [resource]),
                ),
          )
          as _i10.Future<T>);

  @override
  T trackStage<T>(
    String? label,
    T Function()? action, {
    bool? isExternal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #trackStage,
              [label, action],
              {#isExternal: isExternal},
            ),
            returnValue: _i12.dummyValue<T>(
              this,
              Invocation.method(
                #trackStage,
                [label, action],
                {#isExternal: isExternal},
              ),
            ),
            returnValueForMissingStub: _i12.dummyValue<T>(
              this,
              Invocation.method(
                #trackStage,
                [label, action],
                {#isExternal: isExternal},
              ),
            ),
          )
          as T);

  @override
  void reportUnusedAssets(Iterable<_i6.AssetId>? ids) => super.noSuchMethod(
    Invocation.method(#reportUnusedAssets, [ids]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i11.Digest> digest(_i6.AssetId? id) =>
      (super.noSuchMethod(
            Invocation.method(#digest, [id]),
            returnValue: _i10.Future<_i11.Digest>.value(
              _FakeDigest_10(this, Invocation.method(#digest, [id])),
            ),
            returnValueForMissingStub: _i10.Future<_i11.Digest>.value(
              _FakeDigest_10(this, Invocation.method(#digest, [id])),
            ),
          )
          as _i10.Future<_i11.Digest>);
}

/// A class which mocks [DartObject].
///
/// See the documentation for Mockito's code generation for more information.
class MockDartObject extends _i1.Mock implements _i2.DartObject {
  @override
  bool get hasKnownValue =>
      (super.noSuchMethod(
            Invocation.getter(#hasKnownValue),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNull =>
      (super.noSuchMethod(
            Invocation.getter(#isNull),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.DartObject? getField(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getField, [name]),
            returnValueForMissingStub: null,
          )
          as _i2.DartObject?);
}

/// A class which mocks [DartType].
///
/// See the documentation for Mockito's code generation for more information.
class MockDartType extends _i1.Mock implements _i3.DartType {
  @override
  _i3.DartType get extensionTypeErasure =>
      (super.noSuchMethod(
            Invocation.getter(#extensionTypeErasure),
            returnValue: _FakeDartType_2(
              this,
              Invocation.getter(#extensionTypeErasure),
            ),
            returnValueForMissingStub: _FakeDartType_2(
              this,
              Invocation.getter(#extensionTypeErasure),
            ),
          )
          as _i3.DartType);

  @override
  bool get isBottom =>
      (super.noSuchMethod(
            Invocation.getter(#isBottom),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartAsyncFuture =>
      (super.noSuchMethod(
            Invocation.getter(#isDartAsyncFuture),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartAsyncFutureOr =>
      (super.noSuchMethod(
            Invocation.getter(#isDartAsyncFutureOr),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartAsyncStream =>
      (super.noSuchMethod(
            Invocation.getter(#isDartAsyncStream),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreBool =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreBool),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreDouble =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreDouble),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreEnum =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreEnum),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreFunction =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreFunction),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreInt =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreInt),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreIterable =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreIterable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreList =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreList),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreMap =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreMap),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreNull =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreNull),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreNum =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreNum),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreObject =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreObject),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreRecord =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreRecord),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreSet =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreSet),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreString =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreString),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreSymbol =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreSymbol),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDartCoreType =>
      (super.noSuchMethod(
            Invocation.getter(#isDartCoreType),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i18.NullabilitySuffix get nullabilitySuffix =>
      (super.noSuchMethod(
            Invocation.getter(#nullabilitySuffix),
            returnValue: _i18.NullabilitySuffix.question,
            returnValueForMissingStub: _i18.NullabilitySuffix.question,
          )
          as _i18.NullabilitySuffix);

  @override
  R accept<R>(_i19.TypeVisitor<R>? visitor) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [visitor]),
            returnValue: _i12.dummyValue<R>(
              this,
              Invocation.method(#accept, [visitor]),
            ),
            returnValueForMissingStub: _i12.dummyValue<R>(
              this,
              Invocation.method(#accept, [visitor]),
            ),
          )
          as R);

  @override
  R acceptWithArgument<R, A>(
    _i19.TypeVisitorWithArgument<R, A>? visitor,
    A? argument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptWithArgument, [visitor, argument]),
            returnValue: _i12.dummyValue<R>(
              this,
              Invocation.method(#acceptWithArgument, [visitor, argument]),
            ),
            returnValueForMissingStub: _i12.dummyValue<R>(
              this,
              Invocation.method(#acceptWithArgument, [visitor, argument]),
            ),
          )
          as R);

  @override
  _i3.InterfaceType? asInstanceOf(_i7.InterfaceElement? element) =>
      (super.noSuchMethod(
            Invocation.method(#asInstanceOf, [element]),
            returnValueForMissingStub: null,
          )
          as _i3.InterfaceType?);

  @override
  String getDisplayString({bool? withNullability = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayString, [], {
              #withNullability: withNullability,
            }),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getDisplayString, [], {
                #withNullability: withNullability,
              }),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getDisplayString, [], {
                #withNullability: withNullability,
              }),
            ),
          )
          as String);
}

/// A class which mocks [Element].
///
/// See the documentation for Mockito's code generation for more information.
class MockElement extends _i1.Mock implements _i7.Element {
  @override
  _i7.Element get baseElement =>
      (super.noSuchMethod(
            Invocation.getter(#baseElement),
            returnValue: _FakeElement_11(this, Invocation.getter(#baseElement)),
            returnValueForMissingStub: _FakeElement_11(
              this,
              Invocation.getter(#baseElement),
            ),
          )
          as _i7.Element);

  @override
  List<_i7.Element> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: <_i7.Element>[],
            returnValueForMissingStub: <_i7.Element>[],
          )
          as List<_i7.Element>);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  _i7.Fragment get firstFragment =>
      (super.noSuchMethod(
            Invocation.getter(#firstFragment),
            returnValue: _FakeFragment_12(
              this,
              Invocation.getter(#firstFragment),
            ),
            returnValueForMissingStub: _FakeFragment_12(
              this,
              Invocation.getter(#firstFragment),
            ),
          )
          as _i7.Fragment);

  @override
  List<_i7.Fragment> get fragments =>
      (super.noSuchMethod(
            Invocation.getter(#fragments),
            returnValue: <_i7.Fragment>[],
            returnValueForMissingStub: <_i7.Fragment>[],
          )
          as List<_i7.Fragment>);

  @override
  int get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isPrivate =>
      (super.noSuchMethod(
            Invocation.getter(#isPrivate),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPublic =>
      (super.noSuchMethod(
            Invocation.getter(#isPublic),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.ElementKind get kind =>
      (super.noSuchMethod(
            Invocation.getter(#kind),
            returnValue: _FakeElementKind_13(this, Invocation.getter(#kind)),
            returnValueForMissingStub: _FakeElementKind_13(
              this,
              Invocation.getter(#kind),
            ),
          )
          as _i7.ElementKind);

  @override
  _i7.Metadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeMetadata_14(this, Invocation.getter(#metadata)),
            returnValueForMissingStub: _FakeMetadata_14(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i7.Metadata);

  @override
  _i7.Element get nonSynthetic =>
      (super.noSuchMethod(
            Invocation.getter(#nonSynthetic),
            returnValue: _FakeElement_11(
              this,
              Invocation.getter(#nonSynthetic),
            ),
            returnValueForMissingStub: _FakeElement_11(
              this,
              Invocation.getter(#nonSynthetic),
            ),
          )
          as _i7.Element);

  @override
  T? accept<T>(_i7.ElementVisitor2<T>? visitor) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [visitor]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  String displayString({
    bool? multiline = false,
    bool? preferTypeAlias = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#displayString, [], {
              #multiline: multiline,
              #preferTypeAlias: preferTypeAlias,
            }),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#displayString, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#displayString, [], {
                #multiline: multiline,
                #preferTypeAlias: preferTypeAlias,
              }),
            ),
          )
          as String);

  @override
  String getExtendedDisplayName({String? shortName}) =>
      (super.noSuchMethod(
            Invocation.method(#getExtendedDisplayName, [], {
              #shortName: shortName,
            }),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName, [], {
                #shortName: shortName,
              }),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getExtendedDisplayName, [], {
                #shortName: shortName,
              }),
            ),
          )
          as String);

  @override
  bool isAccessibleIn(_i7.LibraryElement? library) =>
      (super.noSuchMethod(
            Invocation.method(#isAccessibleIn, [library]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isDeprecatedWithKind(String? kind) =>
      (super.noSuchMethod(
            Invocation.method(#isDeprecatedWithKind, [kind]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Element? thisOrAncestorMatching(bool Function(_i7.Element)? predicate) =>
      (super.noSuchMethod(
            Invocation.method(#thisOrAncestorMatching, [predicate]),
            returnValueForMissingStub: null,
          )
          as _i7.Element?);

  @override
  void visitChildren<T>(_i7.ElementVisitor2<T>? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildren, [visitor]),
    returnValueForMissingStub: null,
  );
}
