import 'package:svg_painter/src/xml_model/xml_attribute_name.dart';
import 'package:test/test.dart';

void main() {
  group('XmlAttributeName', () {
    test('should map every enum value to the correct SVG attribute string', () {
      // Arrange & Act & Assert
      for (final XmlAttributeName value in XmlAttributeName.values) {
        final String expected = switch (value) {
          XmlAttributeName.className => 'class',
          XmlAttributeName.clipPath => 'clip-path',
          XmlAttributeName.clipPathUnits => 'clipPathUnits',
          XmlAttributeName.color => 'color',
          XmlAttributeName.cx => 'cx',
          XmlAttributeName.cy => 'cy',
          XmlAttributeName.d => 'd',
          XmlAttributeName.decoding => 'decoding',
          XmlAttributeName.dx => 'dx',
          XmlAttributeName.dy => 'dy',
          XmlAttributeName.fill => 'fill',
          XmlAttributeName.fillOpacity => 'fill-opacity',
          XmlAttributeName.fillRule => 'fill-rule',
          XmlAttributeName.fontFamily => 'font-family',
          XmlAttributeName.fontSize => 'font-size',
          XmlAttributeName.fontStyle => 'font-style',
          XmlAttributeName.fontWeight => 'font-weight',
          XmlAttributeName.fr => 'fr',
          XmlAttributeName.fx => 'fx',
          XmlAttributeName.fy => 'fy',
          XmlAttributeName.gradientTransform => 'gradientTransform',
          XmlAttributeName.gradientUnits => 'gradientUnits',
          XmlAttributeName.height => 'height',
          XmlAttributeName.href => 'href',
          XmlAttributeName.id => 'id',
          XmlAttributeName.mask => 'mask',
          XmlAttributeName.maskContentUnits => 'maskContentUnits',
          XmlAttributeName.maskUnits => 'maskUnits',
          XmlAttributeName.media => 'media',
          XmlAttributeName.offset => 'offset',
          XmlAttributeName.opacity => 'opacity',
          XmlAttributeName.paintOrder => 'paint-order',
          XmlAttributeName.pathLength => 'pathLength',
          XmlAttributeName.points => 'points',
          XmlAttributeName.preserveAspectRatio => 'preserveAspectRatio',
          XmlAttributeName.r => 'r',
          XmlAttributeName.rotate => 'rotate',
          XmlAttributeName.rx => 'rx',
          XmlAttributeName.ry => 'ry',
          XmlAttributeName.spreadMethod => 'spreadMethod',
          XmlAttributeName.stopColor => 'stop-color',
          XmlAttributeName.stopOpacity => 'stop-opacity',
          XmlAttributeName.stroke => 'stroke',
          XmlAttributeName.strokeDasharray => 'stroke-dasharray',
          XmlAttributeName.strokeDashoffset => 'stroke-dashoffset',
          XmlAttributeName.strokeLinecap => 'stroke-linecap',
          XmlAttributeName.strokeLinejoin => 'stroke-linejoin',
          XmlAttributeName.strokeMiterlimit => 'stroke-miterlimit',
          XmlAttributeName.strokeOpacity => 'stroke-opacity',
          XmlAttributeName.strokeWidth => 'stroke-width',
          XmlAttributeName.style => 'style',
          XmlAttributeName.textAnchor => 'text-anchor',
          XmlAttributeName.title => 'title',
          XmlAttributeName.transform => 'transform',
          XmlAttributeName.type => 'type',
          XmlAttributeName.vectorEffect => 'vector-effect',
          XmlAttributeName.viewBox => 'viewBox',
          XmlAttributeName.width => 'width',
          XmlAttributeName.x => 'x',
          XmlAttributeName.x1 => 'x1',
          XmlAttributeName.x2 => 'x2',
          XmlAttributeName.xmlSpace => 'xml:space',
          XmlAttributeName.y => 'y',
          XmlAttributeName.y1 => 'y1',
          XmlAttributeName.y2 => 'y2',
        };
        expect(value.name, expected, reason: 'Enum $value should map to "$expected"');
      }
    });
  });
}
