name: svg_painter_annotation
description: Annotations for the svg_painter code generator, enabling compilation of SVGs into Flutter CustomPainters.
version: 0.0.1
repository: https://github.com/tekneurt/svg_painter/tree/master/svg_painter_annotation

environment:
  sdk: ^3.10.4

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.25.6