import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

enum SvgTestType {
  mdn,
  w3c,
  various,
}

Future<void> testSvgPainter({
  required WidgetTester tester,
  required CustomPainter painter,
  required String goldenName,
  String goldenPath = 'goldens',
  Size size = const Size(100, 100),
}) async {
  // Set window properties for consistent goldens and exact framing
  tester.view.devicePixelRatio = 1.0;
  final Size containerSize = Size(size.width + 20, size.height + 20); // Account for 10px border
  tester.view.physicalSize = containerSize;

  await tester.pumpWidget(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Center(
        child: Container(
          width: containerSize.width,
          height: containerSize.height,
          decoration: BoxDecoration(
            border: Border.all(color: Colors.red, width: 10),
            color: Colors.grey[200],
          ),
          child: CustomPaint(size: size, painter: painter),
        ),
      ),
    ),
  );

  await expectLater(find.byType(Container), matchesGoldenFile('$goldenPath/$goldenName'));

  // Reset for next test
  tester.view.resetDevicePixelRatio();
  tester.view.resetPhysicalSize();
}

/// Tests the painter without a defined size, relying on its "native" resolution
/// (which in our implementation should correspond to the viewBox).
Future<void> testSvgPainterNative({
  required WidgetTester tester,
  required CustomPainter painter,
  required String goldenName,
  String goldenPath = 'goldens',
}) async {
  tester.view.devicePixelRatio = 1.0;

  // Use the viewBox getter if available (generated by SvgPainterGenerator)
  // to set the exact surface size.
  final Size size = (painter as dynamic).viewBox as Size;
  tester.view.physicalSize = size;

  await tester.pumpWidget(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Center(
        child: SizedBox(
          width: size.width,
          height: size.height,
          child: CustomPaint(painter: painter),
        ),
      ),
    ),
  );

  await expectLater(find.byType(SizedBox), matchesGoldenFile('$goldenPath/$goldenName'));

  tester.view.resetDevicePixelRatio();
  tester.view.resetPhysicalSize();
}

/// Runs both sized and native tests for a painter.
Future<void> testDualResolutionPainter({
  required WidgetTester tester,
  required CustomPainter painter,
  required String name,
  required SvgTestType type,
  String? folder,
}) async {
  final String goldenPath = switch (type) {
    SvgTestType.mdn || SvgTestType.w3c => '$folder/goldens',
    SvgTestType.various => 'goldens',
  };

  await testSvgPainter(
    tester: tester,
    painter: painter,
    goldenName: '$name.png',
    goldenPath: goldenPath,
    size: const Size(200, 200),
  );

  await testSvgPainterNative(
    tester: tester,
    painter: painter,
    goldenName: '${name}_native.png',
    goldenPath: goldenPath,
  );
}
